CREATE TABLE IF NOT EXISTS "public"."project_updates" (
    "id" bigint NOT NULL,
    "project_id" bigint NOT NULL,
    "title" text NOT NULL,
    "content" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "public"."project_updates" OWNER TO "postgres";

COMMENT ON TABLE "public"."project_updates" IS 'record update for each project';

ALTER TABLE "public"."project_updates"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."project_updates_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY "public"."project_updates"
    ADD CONSTRAINT "project_updates_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."project_updates"
    ADD CONSTRAINT "project_updates_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "public"."projects"("id");

CREATE POLICY "Enable insert for authenticated users only"
    ON "public"."project_updates"
    FOR INSERT
    TO "authenticated"
    WITH CHECK (true);

CREATE POLICY "Enable read access for all users"
    ON "public"."project_updates"
    FOR SELECT
    USING (true);

ALTER TABLE "public"."project_updates" ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE "public"."project_updates" TO "anon";
GRANT ALL ON TABLE "public"."project_updates" TO "authenticated";
GRANT ALL ON TABLE "public"."project_updates" TO "service_role";

GRANT ALL ON SEQUENCE "public"."project_updates_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."project_updates_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."project_updates_id_seq" TO "service_role";
